export const CARRIER_NAMES: Record<string, string> = {
  AA: "American Airlines",
  UA: "United Airlines",
  DL: "Delta Air Lines",
  WN: "Southwest Airlines",
  B6: "JetBlue Airways",
  NK: "Spirit Airlines",
  F9: "Frontier Airlines",
  AS: "Alaska Airlines",
  AC: "Air Canada",
  WS: "WestJet",
  BA: "British Airways",
  LH: "Lufthansa",
  AF: "Air France",
  KL: "KLM",
  IB: "Iberia",
  AZ: "ITA Airways",
  LX: "Swiss International",
  OS: "Austrian Airlines",
  SK: "SAS",
  AY: "Finnair",
  TP: "TAP Air Portugal",
  EK: "Emirates",
  QR: "Qatar Airways",
  EY: "Etihad Airways",
  TK: "Turkish Airlines",
  SQ: "Singapore Airlines",
  CX: "Cathay Pacific",
  NH: "ANA",
  JL: "Japan Airlines",
  KE: "Korean Air",
  OZ: "Asiana Airlines",
  CI: "China Airlines",
  BR: "EVA Air",
  CA: "Air China",
  MU: "China Eastern",
  CZ: "China Southern",
  AI: "Air India",
  QF: "Qantas",
  NZ: "Air New Zealand",
  LA: "LATAM",
  AM: "Aeroméxico",
  CM: "Copa Airlines",
  AV: "Avianca",
};

export function carrierName(code: string): string {
  return CARRIER_NAMES[code] ?? code;
}
